# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Unhandled Expression
tagline:          'Geoffroy Couprie – software security and architecture consultant'
description:      'Geoffroy Couprie – software security and architecture consultant'
url:              http://unhandledexpression.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Geoffroy Couprie'
  url:            https://twitter.com/gcouprie

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.6.0
sidebar_home_link:  true
sidebar_link:       true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

#github:
#  repo:             https://github.com/geal

